// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frerzycqgsazembevrex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZXJ6eWNxZ3NhemVtYmV2cmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTEwNjEsImV4cCI6MjA2NjEyNzA2MX0.VnPZx1ukwljxMY0GGpCJeGky4oNzBMcxUbgsRJHp1iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);